export const ACCOUNT_FORM_NAME = 'account'
export const LOGIN_FORM_NAME = 'login'
export const SIGNUP_FORM_NAME = 'signup'
export const NEW_PROJECT_FORM_NAME = 'newProject'
export const NEW_PROJECT_ANSWER_FORM_NAME = 'newProjectAnswer'
export const EDIT_PROJECT_FORM_NAME = 'editProject'
export const DELETE_PROJECT_FORM_NAME = 'deleteProject'
