export const LIST_PATH = '/products'
export const QUIZ_PATH = '/id:/quiz'
export const ACCOUNT_PATH = '/account'
export const LOGIN_PATH = '/login'
export const SIGNUP_PATH = '/signup'
export const DASHBOARD = '/'
